### ISSUE TITLE
Add option to work with data with and without UMI index

### ISSUE THREAD

**Issue by archanaraja** [MoTrPAC/motrpac-rna-seq-pipeline#53]
Add an option in the pipeline to skip the below tasks if the library doesn't use UMI index.

- attach_umi
- UMI_dup
- make all the umi related input parameters in the config and umi_report option in the collect_qc.wdl and python script optional

**Comment by archanaraja** [comment]
@mihirsamdarshi : As Im just about to test this feature I noticed that the make_json_rnaseq.py doesn't seem to have an option to generate the jsons without the UMI index. ie just R1 and R2 files.

**Comment by mihirsamdarshi** [comment]
No need to use the `sorted/` folder: 
```bash 
❯ gsutil ls gs://omicspipelines/rnaseq/references/rat/                                                                                                                       
gs://omicspipelines/rnaseq/references/rat/Rattus_norvegicus.Rnor_6.0.96.gtf
gs://omicspipelines/rnaseq/references/rat/Rnor6_v96_star_index.tar.gz
gs://omicspipelines/rnaseq/references/rat/phix.tar.gz
gs://omicspipelines/rnaseq/references/rat/refFlat_rn6_v96.txt
gs://omicspipelines/rnaseq/references/rat/rn6_rsem_reference.tar.gz
gs://omicspipelines/rnaseq/references/rat/rn_globin.tar.gz
gs://omicspipelines/rnaseq/references/rat/rn_rRNA.tar.gz
```

**Comment by archanaraja** [comment]
Modify the make_json_rnaseq.py to make the blocks that generates I1 files optional and use the make_json_rnaseq.py from the master but for the two minor changes the pipeline is working

**Comment by biodavidjm** [comment]
@mihirsamdarshi , what is the status of this issue?

**Comment by archanaraja** [comment]
This has been done , tested and merged with master. Thanks @mihirsamdarshi . Also added feature to support new rat reference.
